//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGSA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyOffer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BuyOffer()
        {
            this.Transactions = new HashSet<Transactions>();
        }
    
        public int Id { get; set; }
        public int BuyerId { get; set; }
        public Nullable<double> Price { get; set; }
        public int Amount { get; set; }
        public Nullable<System.DateTime> LastSellDate { get; set; }
        public string Name { get; set; }
        public int SoldCopies { get; set; }
        public int ProductId { get; set; }
        public int StatusId { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int UpdateWho { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Product Product { get; set; }
        public virtual DicOfferStatus DicOfferStatus { get; set; }
        public virtual Users Users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transactions> Transactions { get; set; }
    }
}
