//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGSA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersAuthetication
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Password { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int UpdateWho { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
