//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGSA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MainDatabaseEntities : DbContext
    {
        public MainDatabaseEntities()
            : base("name=MainDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BuyOffer> BuyOffer { get; set; }
        public virtual DbSet<DicCondition> DicCondition { get; set; }
        public virtual DbSet<DicGenre> DicGenre { get; set; }
        public virtual DbSet<DicOfferStatus> DicOfferStatus { get; set; }
        public virtual DbSet<DicProductType> DicProductType { get; set; }
        public virtual DbSet<DicTransactionStatus> DicTransactionStatus { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<SellOffer> SellOffer { get; set; }
        public virtual DbSet<Transactions> Transactions { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UsersAuthetication> UsersAuthetication { get; set; }
    }
}
