//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGSA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.BuyOffer = new HashSet<BuyOffer>();
            this.SellOffer = new HashSet<SellOffer>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<double> Rating { get; set; }
        public int Stock { get; set; }
        public int SoldCopies { get; set; }
        public Nullable<int> GenreId { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public Nullable<int> ConditionId { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int UpdateWho { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuyOffer> BuyOffer { get; set; }
        public virtual DicCondition DicCondition { get; set; }
        public virtual DicGenre DicGenre { get; set; }
        public virtual DicProductType DicProductType { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellOffer> SellOffer { get; set; }
    }
}
