//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGSA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions
    {
        public int Id { get; set; }
        public int SellerId { get; set; }
        public int BuyerId { get; set; }
        public int BuyOfferId { get; set; }
        public int SellOfferId { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int StatusId { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int UpdateWho { get; set; }
    
        public virtual BuyOffer BuyOffer { get; set; }
        public virtual DicTransactionStatus DicTransactionStatus { get; set; }
        public virtual SellOffer SellOffer { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual Users Users2 { get; set; }
    }
}
